DROP TABLE IF EXISTS message;

CREATE TABLE message (
  id INT AUTO_INCREMENT PRIMARY KEY,
  timestamp DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP,
  username VARCHAR(255),
  text TEXT,
  image_url VARCHAR(255),
  extra JSON
);
