/*
 * This file is generated by jOOQ.
*/
package se.olander.konferenschatten.jooq.konferenschatten;


import java.util.ArrayList;
import java.util.Arrays;
import java.util.List;

import javax.annotation.Generated;

import org.jooq.Catalog;
import org.jooq.Table;
import org.jooq.impl.SchemaImpl;

import se.olander.konferenschatten.jooq.DefaultCatalog;
import se.olander.konferenschatten.jooq.konferenschatten.tables.Message;


/**
 * This class is generated by jOOQ.
 */
@Generated(
    value = {
        "http://www.jooq.org",
        "jOOQ version:3.9.5"
    },
    comments = "This class is generated by jOOQ"
)
@SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class Konferenschatten extends SchemaImpl {

    private static final long serialVersionUID = 1804954087;

    /**
     * The reference instance of <code>konferenschatten</code>
     */
    public static final Konferenschatten KONFERENSCHATTEN = new Konferenschatten();

    /**
     * The table <code>konferenschatten.message</code>.
     */
    public final Message MESSAGE = se.olander.konferenschatten.jooq.konferenschatten.tables.Message.MESSAGE;

    /**
     * No further instances allowed
     */
    private Konferenschatten() {
        super(null, null);
    }


    /**
     * {@inheritDoc}
     */
    @Override
    public Catalog getCatalog() {
        return DefaultCatalog.DEFAULT_CATALOG;
    }

    @Override
    public final List<Table<?>> getTables() {
        List result = new ArrayList();
        result.addAll(getTables0());
        return result;
    }

    private final List<Table<?>> getTables0() {
        return Arrays.<Table<?>>asList(
            Message.MESSAGE);
    }
}
