/*
 * This file is generated by jOOQ.
*/
package se.olander.konferenschatten.jooq.konferenschatten;


import javax.annotation.Generated;

import se.olander.konferenschatten.jooq.konferenschatten.tables.Message;


/**
 * Convenience access to all tables in konferenschatten
 */
@Generated(
    value = {
        "http://www.jooq.org",
        "jOOQ version:3.9.3"
    },
    comments = "This class is generated by jOOQ"
)
@SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class Tables {

    /**
     * The table <code>konferenschatten.message</code>.
     */
    public static final Message MESSAGE = se.olander.konferenschatten.jooq.konferenschatten.tables.Message.MESSAGE;
}
