/*
 * This file is generated by jOOQ.
*/
package se.olander.konferenschatten.jooq.konferenschatten;


import javax.annotation.Generated;

import se.olander.konferenschatten.jooq.konferenschatten.tables.Message;
import se.olander.konferenschatten.jooq.konferenschatten.tables.Meta;


/**
 * Convenience access to all tables in konferenschatten
 */
@Generated(
    value = {
        "http://www.jooq.org",
        "jOOQ version:3.9.5"
    },
    comments = "This class is generated by jOOQ"
)
@SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class Tables {

    /**
     * The table <code>konferenschatten.message</code>.
     */
    public static final Message MESSAGE = se.olander.konferenschatten.jooq.konferenschatten.tables.Message.MESSAGE;

    /**
     * The table <code>konferenschatten.meta</code>.
     */
    public static final Meta META = se.olander.konferenschatten.jooq.konferenschatten.tables.Meta.META;
}
