/*
 * This file is generated by jOOQ.
*/
package se.olander.konferenschatten.jooq.konferenschatten.tables.daos;


import java.sql.Timestamp;
import java.util.List;

import javax.annotation.Generated;

import org.jooq.Configuration;
import org.jooq.impl.DAOImpl;

import se.olander.konferenschatten.jooq.konferenschatten.tables.Meta;
import se.olander.konferenschatten.jooq.konferenschatten.tables.records.MetaRecord;


/**
 * This class is generated by jOOQ.
 */
@Generated(
    value = {
        "http://www.jooq.org",
        "jOOQ version:3.9.5"
    },
    comments = "This class is generated by jOOQ"
)
@SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class MetaDao extends DAOImpl<MetaRecord, se.olander.konferenschatten.jooq.konferenschatten.tables.pojos.Meta, Integer> {

    /**
     * Create a new MetaDao without any configuration
     */
    public MetaDao() {
        super(Meta.META, se.olander.konferenschatten.jooq.konferenschatten.tables.pojos.Meta.class);
    }

    /**
     * Create a new MetaDao with an attached configuration
     */
    public MetaDao(Configuration configuration) {
        super(Meta.META, se.olander.konferenschatten.jooq.konferenschatten.tables.pojos.Meta.class, configuration);
    }

    /**
     * {@inheritDoc}
     */
    @Override
    protected Integer getId(se.olander.konferenschatten.jooq.konferenschatten.tables.pojos.Meta object) {
        return object.getId();
    }

    /**
     * Fetch records that have <code>id IN (values)</code>
     */
    public List<se.olander.konferenschatten.jooq.konferenschatten.tables.pojos.Meta> fetchById(Integer... values) {
        return fetch(Meta.META.ID, values);
    }

    /**
     * Fetch a unique record that has <code>id = value</code>
     */
    public se.olander.konferenschatten.jooq.konferenschatten.tables.pojos.Meta fetchOneById(Integer value) {
        return fetchOne(Meta.META.ID, value);
    }

    /**
     * Fetch records that have <code>timestamp IN (values)</code>
     */
    public List<se.olander.konferenschatten.jooq.konferenschatten.tables.pojos.Meta> fetchByTimestamp(Timestamp... values) {
        return fetch(Meta.META.TIMESTAMP, values);
    }

    /**
     * Fetch records that have <code>username IN (values)</code>
     */
    public List<se.olander.konferenschatten.jooq.konferenschatten.tables.pojos.Meta> fetchByUsername(String... values) {
        return fetch(Meta.META.USERNAME, values);
    }

    /**
     * Fetch records that have <code>data IN (values)</code>
     */
    public List<se.olander.konferenschatten.jooq.konferenschatten.tables.pojos.Meta> fetchByData(Object... values) {
        return fetch(Meta.META.DATA, values);
    }
}
